services:
  - type: web
    name: grievance_system
    runtime: php
    buildCommand: "./build.sh"
    startCommand: "php -S 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grievance-db
          property: connectionString